import SignupForm from '@/components/SignupForm'
import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "SignUp",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
        <SignupForm />
    </div>
  )
}

export default page