import LoginForm from '@/components/LoginForm'
import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
        <LoginForm />
    </div>
  )
}

export default page